### ISSUE TITLE
Subcategories work-around

### ISSUE THREAD

**Issue by RealTayy** [thaiscmky/phonow#193]
Hi if adding subcategories to the database is taking too long and too much effort this is my proposed work-around:

I will hard code the two categories that require subcategories. So that when we click relevant menu button on main.menu VIEW. Those 3 categories will pop up for those menus. We still still be able to add items to those categories. We will still be able to add new categories (probably... btw adding new categories is not MVP just new menu items is).

The only difference is that we will have a few menu buttons that are static and can't be removed (Noodle Soup & Rice/Vermicilli)

**Comment by thaiscmky** [comment]
Categories with soft relationship and no foreign keys added to the data schema.
