### ISSUE TITLE
Write file naming convention on wiki

### ISSUE THREAD

**Issue by thaiscmky** [thaiscmky/phonow#28]
Modal names
Modal js file names
Table names
etc.

**Comment by molinacarlosdev** [comment]
Done, please review and advise me if we need to change things.

**Comment by thaiscmky** [comment]
@molinacarlosdev reviewed; looks great to me! Only thing added was the snake and kebab casing discussed after class
https://github.com/thaiscmky/phonow/wiki/06.-File-Naming-Convention
