### ISSUE TITLE
oAuth implementation -

### ISSUE THREAD

**Issue by molinacarlosdev** [thaiscmky/phonow#63]
Given the route /admin for the administrators

Task:
- Make sure user is authenticated in order to redirect to Dashboard.
- If not authenticated, redirect to a 403 page or something like that.

**Comment by molinacarlosdev** [comment]
FYI - In order for oAuth to work once the project has been deployed, we will need to add the URI address to our app credentials in the google console.

**Comment by thaiscmky** [comment]
> We will need to add the URI address to our app credentials in the google console
@molinacarlosdev Create a task for it if there isn't one already; add details to task for whoever's going to work on it
